version: '3'
services:
  auth:
    build: ./auth
    ports:
      - "3001:3001"
    environment:
      - SECRET_KEY=tu_clave_secreta_aqui

  saludo:
    build: ./saludo
    ports:
      - "3002:3002"
    environment:
      - SECRET_KEY=tu_clave_secreta_aqui

  cliente:
    build: ./cliente
    depends_on:
      - auth
      - saludo
    environment:
      - AUTH_URL=http://auth:3001/login
      - GREETING_URL=http://saludo:3002/saludo