global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'app'
    static_configs:
      - targets: ['app:5000']

  - job_name: 'notification_service'
    static_configs:
      - targets: ['notification_service:5005']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']