global:
  scrape_interval: 15s
rule_files:
  - 'rules.yml'
alerting:
  alertmanagers:
    - static_configs:
        - targets: 
          - alertmanager:9093
scrape_configs:
  - job_name: 'python_app'
    static_configs:
      - targets: ['python_app:5000']

  - job_name: 'notification_service'
    static_configs:
      - targets: 
        - notification_service:5005

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'mysqld_exporter'
    static_configs:
      - targets: ['mysqld_exporter:9104']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15672']

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']

  - job_name: 'logstash'
    static_configs:
      - targets: ['logstash:5044']

  - job_name: 'kibana'
    static_configs:
      - targets: ['kibana:5601']

  - job_name: 'jenkins'
    metrics_path: /prometheus
    static_configs:
      - targets: ['jenkins:8080']

  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']