version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: logs
    ports:
      - "3306:3306"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  log-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - rabbitmq

  auth-service:
    build:
      context: ./auth-service
    ports:
      - "8081:8081"
    depends_on:
      - log-service

  tests:
    build: .
    command: go test ./tests
    depends_on:
      - log-service
      - auth-service